# config.yaml
database:
  driver: mysql
  host: localhost
  port: 3306
  user: root
  password:
  name: fas

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret_key: asdasdasdasd
